#    MIDI player base on timidity and imgui, support soundfont(SF2) and software MIDI keyboard.
#    Copyright (C) 2023  Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

name: immidi # you probably want to 'snapcraft register <name>'
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MIDI player base on timidity and imgui. # 79 char long summary
description: |
  MIDI player base on timidity and imgui, support soundfont(SF2) and software MIDI keyboard.

  **For playing midi successfully, the soundfont is necessary. **
  
     ~/snap/immidi/current/.config/MIDI Player/soundfont/

  _More details: https://github.com/Joker2770/immidi-snap.git_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
license: 'MIT'

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/pulse:
    bind: $SNAP/etc/pulse
  /usr/local/share:
    bind: $SNAP/usr/local/share
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules

apps:
  immidi:
    command: desktop-launch $SNAP/usr/local/bin/immidi
    command-chain:
      - bin/desktop-launch
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - pulseaudio
      - alsa
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - gsettings
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
    environment:
      DISABLE_WAYLAND: 1
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      # QT_QPA_PLATFORMTHEME: gtk3

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  immidi:
    after: [alsa-mixin]
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DIMGUI_VULKAN_SHADER=OFF"
    source: https://github.com/Joker2770/libmidi.git
    source-type: git
    source-branch: main
    source-depth: 1
    build-packages:
      - gcc
      - g++
      - make
      - spirv-tools
      - glslang-dev
      - libgmp-dev
      - libglew-dev
      - libglfw3-dev
      - libncurses-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libfreetype-dev
      - libgl1-mesa-dev
      - libvulkan-dev
    stage-packages:
      - libgmp10
      - libgl1
      - libglx-mesa0
      - libglew2.1
      - glewlwyd
      - libglfw3
      - libglfw3-wayland
      - libncurses6
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libvulkan1


