#    MIDI player base on timidity and imgui, support soundfont(SF2) and software MIDI keyboard.
#    Copyright (C) 2023-2024  Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

name: immidi # you probably want to 'snapcraft register <name>'
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MIDI player base on timidity and imgui. # 79 char long summary
description: |
  MIDI player base on timidity and imgui, support soundfont(SF2) and software MIDI keyboard.

  **If you have customized soundfont, could copy them into the path as follow. **
  
     ~/snap/immidi/current/.config/MIDI Player/soundfont/

  _More details: https://github.com/Joker2770/immidi-snap.git_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22
license: 'MIT'
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /etc/pulse:
    bind: $SNAP/etc/pulse
  /usr/local/share:
    bind: $SNAP/usr/local/share
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0/modules

apps:
  immidi:
    command: usr/local/bin/immidi
    command-chain: ["bin/desktop-launch"]
    environment:
      LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib"
    # extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - pulseaudio
      - alsa
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - gsettings
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
      - qualcomm-ipc-router
      - firewall-control
      - netlink-connector
      - netlink-audit
      - network
      - network-bind
      - network-manager
      - network-manager-observe
      - network-control
  timidity:
    command: usr/local/bin/timidity
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib
    # extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - pulseaudio
      - alsa
      - removable-media
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
  sample:
    command: usr/local/bin/sample
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib
    # extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - pulseaudio
      - alsa
      - removable-media
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
      - qualcomm-ipc-router
      - firewall-control
      - netlink-connector
      - netlink-audit
      - network
      - network-bind
      - network-manager
      - network-manager-observe
      - network-control
  bin2c:
    command: usr/local/bin/bin2c
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/local/lib
    # extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - pulseaudio
      - alsa
      - removable-media
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - system-trace
      - qualcomm-ipc-router
      - firewall-control
      - netlink-connector
      - netlink-audit
      - network
      - network-bind
      - network-manager
      - network-manager-observe
      - network-control

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
  immidi:
    after: [desktop-glib-only]
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DIMGUI_VULKAN_SHADER=OFF"
    source: https://github.com/opencodewin/libmidi.git
    source-type: git
    source-branch: main
    source-depth: 1
    build-packages:
      - gcc
      - g++
      - make
      - spirv-tools
      - glslang-dev
      - libgmp-dev
      - libglew-dev
      - libglfw3-dev
      - libncurses-dev
      - libsdl2-dev
      # - libsdl2-image-dev
      - libfreetype-dev
      # - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libvulkan-dev
      - libimgui-dev
      - libglm-dev
      - libssl-dev
    stage-packages:
      - libgmp10
      - libgl1
      # - libglx-mesa0
      - libglu1-mesa
      # - libglew2.1 #core20
      - libglew2.2 #core22
      - libglfw3
      - libgomp1
      - libncurses6
      - libsdl2-2.0-0
      # - libsdl2-image-2.0-0
      # - libvulkan1
    override-build: |
      cmake ${SNAPCRAFT_PART_BUILD}/../src/ -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DIMGUI_VULKAN_SHADER=OFF
      make -j $(nproc)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/lib
      cp -r --preserve=mode ./immidi ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      cp -r --preserve=mode ./timidity ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      cp -r --preserve=mode ./sample ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      cp -r --preserve=mode ./bin2c ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/
      cp -P ./lib*.so* ${SNAPCRAFT_PART_INSTALL}/usr/local/lib/


